### ISSUE TITLE
1.9 - Block changes color upon chiseling

### ISSUE THREAD

**Issue by codygsmith** [ChiselsAndBits/FlatColoredBlocks#17]
I hope this hasn't been addressed elsewhere - I read this thread and didn't see anything.

I'm using MultiMC 5 v.0.4.11-751 to create a 1.9 instance with Forge 12.16.0.1817, C&B 9.9, FCB 2.2 & JEI 3.1.2.172.

When I create a single player world, creative, place a dark red block #0, left click it with a diamond chisel, the block turns a sort of grayish blue.

Here's a gif: I picked a different block to make the color change more noticeable.
https://giphy.com/gifs/BSgNdnGPARzdm

I'm sorry if I missed something! Thank you so much for taking the time to create this for the community _and_ maintain it! I'm really excited to use this on my first 1.9 server.

**Comment by AlgorithmX2** [comment]
Fixed in C&B 9.10
