### ISSUE TITLE
Crash when breaking glass blocks

### ISSUE THREAD

**Issue by Jayceena** [ChiselsAndBits/FlatColoredBlocks#18]
When in survival mode trying to break a colored glass the moment I start breaking the block my game freezes for a second and then crashes. It only appears to be the glass and I have tried a few different colors and all result in a crash. I'm running v3.1 for Minecraft 1.9.4

If my skills of adding things works then here is my crash log V V V

[crash-2016-06-28_18.48.17-client.txt](https://github.com/AlgorithmX2/FlatColoredBlocks/files/338209/crash-2016-06-28_18.48.17-client.txt)

**Comment by AlgorithmX2** [comment]
Thanks should be fixed in the next build. ( 3.2 or 4.1 )
