### ISSUE TITLE
Bug - Using certain levels of blocks with the latest version overwrites the blocks at relog.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/FlatColoredBlocks#23]
Title says it all.

**Comment by AlgorithmX2** [comment]
I don't know what you means whats does "Using certain levels of blocks" mean?

Are you changing the configs? If so then yes that will change all the colors, This is a documented behavior.

**Comment by P3rf3ctXZer0** [comment]
yes I understand that but are the blocks supposed to overwrite other NBT tables like those used by pokecube on relog? Seeing the instances for yourself is going to be faster. Here is the link. 

https://docs.google.com/document/d/1F0oKJpR1eMcafyi0VF2oYD6M0CBRbAEbJgz9iZgxreI/edit?usp=sharing

**Comment by AlgorithmX2** [comment]
If your blocks are changing from one type to another ( Mod A to Mod B ), that sounds like a forge issue, The colors from FCB will all change, but it will just add a few new blocks or remove a few blocks if needed it won't conflict with a second mod.

Unless you have something else installed that does something that would break forge of course.

FCB is one of the simpler mods around, besides a few fancy rendering tricks and some math that calculates how many blocks it needs to make.
