### ISSUE TITLE
crash while loading Minecraft

### ISSUE THREAD

**Issue by 0Navis0** [ChiselsAndBits/FlatColoredBlocks#24]
I get this crash when I load Minecraft, I'm not sure what causes it. http://pastebin.com/FpAaZHFw

**Comment by AlgorithmX2** [comment]
I'm afraid I don't know either, the vanilla code that Is used for generating MC Models is crashing when FCB calls it, maybe try different mod combinations?

I'd suggest starting by trying without optifine, and then maybe some of the mods with coremods to see if you can track down whatever seems to be causing vanilla code to break when used by FCB.

**Comment by 0Navis0** [comment]
I will do it tomorrow because here I'm tired and I have to wake up early, I will try to find what causes the problem.

**Comment by 0Navis0** [comment]
Okay I think that the problem comes from the new version of Extra Utilities.

**Comment by ricko1** [comment]
I can confirm that it is Extra Utilities 2. I had the same crash and rolling alpha-1.1.0a back to alpha-1.0.1 fixed the crash

**Comment by abdullamu** [comment]
same crash here

**Comment by 0Navis0** [comment]
In fact 3 mods are involved in the crash, the crashes happens only if Optifine is present. It is exactly the same kind of crash than with RandomThings. https://github.com/lumien231/Random-Things/issues/142

**Comment by sp614x** [comment]
Found the problem, it only happens with mods which use delayed sprite registration.
Updated preview OptiFine C4 with a bugfix.
