### ISSUE TITLE
Lighting and more

### ISSUE THREAD

**Issue by MvOGithub** [ChiselsAndBits/FlatColoredBlocks#26]
Hello AlgorithmX2!

Me and my friend are creating a modpack, and so far this is one of the best mods we have (in my opinion). It's not that it's a technical mod, or anything like that. It's just a great addition, in combination with Flat Colored Blocks and Chiseled Me. But I have a question (and also a suggestion). I think this mod would be even better if we could have lighting for the small blocks, that you can turn on and off in the settings, and I would also like it if we had minichests and torches. If you wish, I could help you with that. I don't think you would need help, and I'm definitely not good at making mods, but I do have some programming experience, with Unity and Python. I have tried modding for Minecraft, but it's quite a lot of work haha. If you would like to contact me, add me on Discord: https://discord.gg/hmEVS7Z
If you have any issue connecting to the Discord, let me know through mail: luuk.van.oijen@gmail.com Then I'll change the server position from Amsterdam to somewhere closer to you.

Thanks for creating a great mod.
Sincerely,
Luuk van Oijen, part of Team TaL Wolf

PS Don't mind the profile picture, I accidentally linked my Gamejolt account with this haha.

**Comment by AlgorithmX2** [comment]
First, I assume your talkinga bout C&B and not FCB ( which you posted on )

Lighting can be provided with glowing blocks, including those in FCB, or glowstone, you can adjust how much is required to make it glow in the config if you like.

I don't think mini torches or chests really belong in C&B, someone could make them with another mod and make the MCMP compatible if they wanted too.

**Comment by MvOGithub** [comment]
Yes I was talking about C&B, but I accidentally posted this on FCB. And I should've been more clear about the lighting. I meant that I wanted shadows within the small blocks. If I were to hollow out a block, it's still really bright inside, even if there isnt any light getting in. I guess this is just an issue with the minecraft smooth lighting, but I thought that maybe that information could be useful to me. Thanks for answering, and for the tiny chests etc I'll have to make some blocks that are compatible, but I don't know how yet. You din't

**Comment by MvOGithub** [comment]
Ah ****, on mobile and messed up. I don't need an explanation on how to make them compatible, as I would prefer you to make some great mods instead haha. Thanks for your answer, I appreciate it.
