### ISSUE TITLE
RGB picker

### ISSUE THREAD

**Issue by pckuijper** [ChiselsAndBits/FlatColoredBlocks#29]
Would it be possible to add some kind of RGB color picker so that you could exactly fine-tune the colors?
Maybe this could be in some form of table (I believe something like this was suggested in another issue #22) where you can dump dye's and materials and pick your color (or put in an exact RGB hex value)

**Comment by AlgorithmX2** [comment]
Duplicate of https://github.com/AlgorithmX2/FlatColoredBlocks/issues/10
