### ISSUE TITLE
[1.8.9] Crash when opening creative menu search

### ISSUE THREAD

**Issue by GirafiStudios** [ChiselsAndBits/FlatColoredBlocks#3]
Just updated to the 1.8.9 version of FCB, didn't happen in the previous version.

Forge  version: 11.15.0.1686
FCB version: v1.4
Crashlog: https://gist.github.com/GirafiStudios/0e9370a9497c4f094eba

**Comment by AlgorithmX2** [comment]
Did you adjust any of your settings or are you running the default? ( if you have changed your settings please provide them ).

**Comment by GirafiStudios** [comment]
Just default, haven't changed anything at all :)

**Comment by AlgorithmX2** [comment]
Interesting, I didn't have any issues when I tested it before release, I'll look into it and see if I can find something.

**Comment by GirafiStudios** [comment]
Ugh. Just tried with a fresh config and a new world. Apparently it doesn't happen there o.O Did you change something related to the config in the latest version? :)

**Comment by AlgorithmX2** [comment]
Nope, 1.3 -> 1.4 was JEI, and a few minor tweaks in the model genrator.

1.2 -> 1.3 basically was no change at all, just added 1.8.9 as a accepted version.

Which Build were you on prior?

**Comment by GirafiStudios** [comment]
I was on 1.3. I think the config file was generated in 1.2 tho :)

**Comment by AlgorithmX2** [comment]
Hmm Maybe post your config anyhow.

**Comment by GirafiStudios** [comment]
This was the config I got the crash on: https://gist.github.com/GirafiStudios/ec7515a3d5b0362cd403

**Comment by AlgorithmX2** [comment]
Ok i'll check it out later tonight, see if I can figure it out.

**Comment by GirafiStudios** [comment]
(Y)

**Comment by AlgorithmX2** [comment]
Can you try this build, https://dl.dropboxusercontent.com/u/9117298/cb/flatcoloredblocks-mc1.8.9-v1.4.jar

I wasn't able to come up with anything truly concrete, but there is only one number that looks like it could be off.

and when I tested it with the config you sent me.. nothing was broken.

**Comment by GirafiStudios** [comment]
I can't reproduce it with the new build ^^ Good job!

**Comment by AlgorithmX2** [comment]
Cool released build.
