### ISSUE TITLE
[1.11]Cannot craft few items

### ISSUE THREAD

**Issue by Myknakryu** [ChiselsAndBits/FlatColoredBlocks#30]
Using:
Minecraft version: 1.11
Forge version: 2180
Flat Colored Blocks version: 1.11 5.0

After installing FCB i cannot craft some items. For example can't craft red dye from poppy. Also removing all mods and leaving only FCB still this happens.

Screenshots:
http://imgur.com/pVkH4fy
http://imgur.com/EQstG7D

**Comment by AlgorithmX2** [comment]
Fixed in v5.1
