### ISSUE TITLE
[Suggestion] Display Hex Code for Flat Colored Block

### ISSUE THREAD

**Issue by frozenLake** [ChiselsAndBits/FlatColoredBlocks#31]
I figure this might be a useful feature to have, as I have tried looking through all the shades of green created by the tool, and I was unable to tell which one was the purest green. (#00FF00 in this case.) Adding a line to the description would do some good in getting specific shades of colors, and I can't really see an issue in implementing it.

**Comment by AlgorithmX2** [comment]
Is there a problem with the current R G B or H S V display that makes hex a better method? For most purposes they seem mostly interchangeable.
