### ISSUE TITLE
It keeps crashing

### ISSUE THREAD

**Issue by Toastluver35** [ChiselsAndBits/FlatColoredBlocks#32]
Everytime I try to load up minecraft with this mod in the game folder it crashes. I'm using the 1.8 file for this mod

**Comment by AlgorithmX2** [comment]
You need to give a crash log.

**Comment by Toastluver35** [comment]
Here is the crash report i recieved

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.8-1.4.9.jar)
  BOPLoadingPlugin (Biomes-O-Plenty-Mod-1.8.jar)
  WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  FairyLightsLoadingPlugin (fairylights-1.1-1.8.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.6.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/15/16 4:33 PM
Description: There was a severe problem during mod loading that has caused
the game to fail

net.minecraftforge.fml.common.LoaderException:
java.lang.NoClassDefFoundError: mezz/jei/api/JEIManager
at
net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
at
net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
at net.minecraft.client.main.Main.main(SourceFile:120)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mezz/jei/api/JEIManager
at
mod.flatcoloredblocks.integration.IntegerationJEI.sendtoJEI(IntegerationJEI.java:39)
at
mod.flatcoloredblocks.integration.IntegerationJEI.init(IntegerationJEI.java:31)
at mod.flatcoloredblocks.FlatColoredBlocks.init(FlatColoredBlocks.java:132)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:553)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
... 10 more
Caused by: java.lang.ClassNotFoundException: mezz.jei.api.JEIManager
at
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 39 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.8
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 326730360 bytes (311 MB) / 707719168 bytes (674 MB) up to
1060372480 bytes (1011 MB)
JVM Flags: 6 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode
-XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 33 mods loaded,
33 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored
UCHI mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHI FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.4.1563.jar)
UCHI Forge{11.14.4.1563} [Minecraft Forge] (forge-1.8-11.14.4.1563.jar)
UCHI Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar)
UCHI BiomesOPlenty{3.0.0} [Biomes O' Plenty] (Biomes-O-Plenty-Mod-1.8.jar)
UCHI cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.jar)
UCHI chiselsandbits{1.0} [Chisels & Bits] (Chisels-and-Bits-Mod-1.8.jar)
UCHI colorfularmor{1.8-2.9} [Colorful Armor] (colorfultools-1.8-2.9.jar)
UCHI colorfularmor2{1.8-1.0} [Colorful Armor 2] (colorfultools-1.8-2.9.jar)
UCHI colorfultools{1.8-1.9} [Colorful Tools] (colorfultools-1.8-2.9.jar)
UCHI random{1.7.10-2.1} [Random Randomness] (colorfultools-1.8-2.9.jar)
UCHI TorqueboltsRecipes{1.0} [TorqueboltsRecipes]
(colorfultools-1.8-2.9.jar)
UCHI CookingPlus{0.6} [CookingPlus] (Cooking-Plus-Mod-1.8.jar)
UCHI customnpcs{1.8.0} [CustomNPCs] (Custom-NPCs-Mod-1.8.jar)
UCHI MoCreatures{8.0.0.devA} [DrZhark's Mo'Creatures Mod] (DrZharks
MoCreatures Mod-8.0.0.devA.jar)
UCHI fairylights{1.1} [Fairy Lights] (fairylights-1.1-1.8.jar)
UCHE flatcoloredblocks{mc1.8.x-v1.1} [Flat Colored Blocks]
(flatcoloredblocks-mc1.8.x-v1.1.jar)
UCHI InventoryPets{1.4.8} [Inventory Pets]
(inventorypets-1.8-1.4.8-universal.jar)
UCHI JEI{2.14.0.139} [Just Enough Items] (jei_1.8-2.14.0.139.jar)
UCHI jrfpaintings{v1.8-00.04.00} [Uncle Jeff's Paintings Mod]
(jrfpaintings-1.8-00.04.00.jar)
UCHI LotsOfFood{1.9.0} [Lots of Food] (Lots of Food-1.9.0.jar)
UCHI lucky{6.0.1} [Lucky Block] (LuckyBlock_1-8_v6-0-1.zip)
UCHI malisiscore{1.8-1.4.9} [MalisisCore] (malisiscore-1.8-1.4.9.jar)
UCHI malisisdoors{1.8-2.5.4} [MalisisDoors] (malisisdoors-1.8-2.5.4.jar)
UCHI chef{5.2} [Master Chef] (Master_Chef_v5.2-1.8.jar)
UCHI RadixCore{1.8-2.1.0} [RadixCore] (RadixCore-1.8-2.1.0-universal.jar)
UCHI MCA{1.8-5.1.1.2} [Minecraft Comes Alive]
(MCA-1.8-5.1.1.2-universal.jar)
UCHI moreplayermodels{1.8.0_beta} [MorePlayerModels]
(MorePlayerModels_1.8.0.jar)
UCHI RandomThings{3.5.6} [Random Things] (RandomThings-MC1.8-3.5.6.jar)
UCHI soggytransportation{4.0.0} [SoggyMustache's Transportation]
(soggytransportation- 4.5.2 (1.8).jar)
UCHI UsefulFood{1.5.0} [UsefulFood] (UsefulFood-1.8-1.5.0a.jar)
UCHI wallpaper{0.9} [Wallpaper] (wallpaper-0.9-1.8.jar)
UCHI XaeroMinimap{1.9.1.1} [Xaero's Minimap]
(Xaeros_Minimap_1.9.1.1_Forge_1.8.jar)
Loaded coremods (and transformers):
MalisisCorePlugin (malisiscore-1.8-1.4.9.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
BOPLoadingPlugin (Biomes-O-Plenty-Mod-1.8.jar)

WallpaperLoadingPlugin (wallpaper-0.9-1.8.jar)
  com.pau101.wallpaper.core.WallpaperClassTransformer
FairyLightsLoadingPlugin (fairylights-1.1-1.8.jar)
  com.pau101.fairylights.core.FairyLightsClassTransformer
LoadingPlugin (RandomThings-MC1.8-3.5.6.jar)
  lumien.randomthings.asm.ClassTransformer
GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.3517' Renderer:
'Intel(R) HD Graphics 2000'

**Comment by AlgorithmX2** [comment]
Looks like the version of JEI your using isn't supported by the version of FlatColoredBlocks.

You on MC 1.8 however, which hasn't been supported in sometime. I can only suggest trying a newer version of JEI.

**Comment by Toastluver35** [comment]
I cannot upgrade my JEI to a later version because me and my cousin play
together via 1.8 modded and thats all he can run, is there any way i can
fix this problem otherwise? I would really like it for your chisels and
bits mod

**Comment by AlgorithmX2** [comment]
Your using the latest version of JEI for 1.8?

Other wise you'll need to re-build one of the two mods to use the same API, or remove the API from FCB and rebuild it.
