### ISSUE TITLE
Crash with ExtraUtilities2 on 1.10.2

### ISSUE THREAD

**Issue by GeorgiaGames2** [ChiselsAndBits/FlatColoredBlocks#33]
I think that this crash is created more by the ExtraUtilities side of the problem, but maybe you have some insight into why this would be happening. There is one older ExtraUtilities version where the two mods work together but all the newer versions crash when I put them together. Sorry that the crash report isn't concealed in one of those drop down menus, I don't know how to do it. Here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.10.2-4.2.9 (1).jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.5.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 1/1/17 3:15 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:205)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:205)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1333977368 bytes (1272 MB) / 3173466112 bytes (3026 MB) up to 4241293312 bytes (4044 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	JEI{3.13.6.393} [Just Enough Items] (jei_1.10.2-3.13.6.393.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	thedragonlib{1.10.2-1.0.3.0} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.0.jar) 
	UCHIJA	armorplus{1.10.2-8.2.2.3} [ArmorPlus] (armorplus-1.10.2-8.2.2.3.jar) 
	UCHIJA	Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
	UCHIJA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11-EDIT.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2089} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2089-EDIT-universal.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	craftablehorsearmour{1.2} [Craftable Horse Armour [CHA&S]] (CraftableHorseArmor-1.3.0-1.10.jar) 
	UCHIJA	craftablenametags{1.2} [Craftable Name Tags] (craftablenametags-1.2.jar) 
	UCHIJA	customspawner{3.10.1} [DrZhark's CustomSpawner] (CustomMobSpawner 3.10.1.jar) 
	UCHIJA	cutepuppymod{1.1} [CutePuppyMod] (CutePuppyMod-1.10.2-1.1.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJA	DragonMounts{r46-1.10.2} [Dragon Mounts] (DragonMounts-r46-1.10.2.jar) 
	UCHIJA	mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-10.0.6.jar) 
	UCHIJA	earthlifemod{0.4} [Earth Life] (EarthLife-0.4a.jar) 
	UCHIJA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3c.jar) 
	UCHIJA	ezstorage{2.2.6} [EZStorage 2] (ezstorage-2.2.6.jar) 
	UCHIJA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.2.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJA	InventoryPets{1.4.8.2} [Inventory Pets] (inventorypets-1.10-1.4.8.2.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	jlgm_caod{1.10.2-0.1.0-hotfixOfTheHotfix} [Cock-an-ore-doo] (jlgm_caod-1.10.2-0.1.0-hotfixOfTheHotfix.jar) 
	UCHIJA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJA	lucky{7.3.0} [Lucky Block] (LuckyBlock_1-10-2_v7-3-0.zip) 
	UCHIJA	malisiscore{1.10.2-4.2.9} [MalisisCore] (malisiscore-1.10.2-4.2.9 (1).jar) 
	UCHIJA	malisisblocks{1.10.2-4.1.3} [Malisis Blocks] (malisisblocks-1.10.2-4.1.3.jar) 
	UCHIJA	malisisdoors{1.10.2-5.1.6} [MalisisDoors] (malisisdoors-1.10.2-5.1.6 (1).jar) 
	UCHIJA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal-EDIT.jar) 
	UCHIJA	shear{1.1.2} [More Shearables] (MoreShearables1.2.1-1.10.2.jar) 
	UCHIJA	shetiphiancore{3.3.5} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.5.jar) 
	UCHIJA	multibeds{1.2.3} [Multi-Beds] (multibeds-1.10.0-1.2.3.jar) 
	UCHIJA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	platforms{1.2.7} [Platforms] (platforms-1.10.0-1.2.7.jar) 
	UCHIJA	ProjectE{1.10.2-PE1.0.6B} [ProjectE] (ProjectE-1.10.2-PE1.0.6B.jar) 
	UCHIJA	randomthings{3.7.7} [Random Things] (RandomThings-MC1.10.2-3.7.7.jar) 
	UCHIJA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.10-1.3.jar) 
	UCHIJA	slabcraftmod{6.03} [Slabcraft] (Slabcraftmod v6.03 - MC1.10.2 Forge (1).jar) 
	UCHIJA	SophisticatedWolves{3.6.1} [SophisticatedWolves] (sophistacedwolves 3.6.3-EDIT-other copy.jar) 
	UCHIJA	spawnercraft{3.1} [SpawnerCraft] (SpawnerCraft 1.10.2-3.2.0.jar) 
	UCHIJA	staircraftmod{6.02} [Staircraft] (Staircraftmod v6.02 - MC1.10.2 Forge.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHIJA	lteleporters{1.1.3} [Lemon's Simple Teleporters] (teleporters-1.1.3.jar) 
	UCHIJA	thedragoncore{1.1.0} [TheDragonCore] (thedragoncore-1.1.0.jar) 
	UCHIJA	thutcore{3.11.1} [ThutCore] (thutcore-3.11.1.jar) 
	UCHIJA	thuttech{@VERSION@} [Thut's Tech] (thuttech-4.0.10.b.jar) 
	UCHIJA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJA	tinkertoolleveling{1.10.2-0.1.0.DEV.b5240c7} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-0.1.0.jar) 
	UCHIJA	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHIJA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.212.jar) 
	UCHIJA	wawla{2.3.1.212} [What Are We Looking At] (Wawla-1.10.2-2.3.1.212.jar) 
	UCHIJA	worldedit{6.1.3} [WorldEdit] (worldedit-forge-mc1.9.4-6.1.3-dist.jar) 
	UCHIJA	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.6-mf-1.10.2-12.18.2.2125.jar) 
	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.10.2-4.2.9 (1).jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  lumien.randomthings.asm.ClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.5.jar)
  shetiphian.core.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.2
	OpenGL: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-10.22.25, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Everthing-EDIT, Glass CT add on-1.10
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 2.1 INTEL-10.22.25
	OpenGlRenderer: Intel(R) Iris(TM) Graphics 6100
	OpenGlVendor: Intel Inc.
	CpuCount: 4

**Comment by AlgorithmX2** [comment]
I'm afraid I have no idea why extra utilities texture loader would be crashing with FlatColoredBlocks, it seems like its calling a method that is private, so maybe that has to do with it?

Flat Colored Blocks doesn't reflect, or transform any fields or methods, so i don't really have any insight into what might cause an issue when both mods are installed.

**Comment by GeorgiaGames2** [comment]
Yeah. Thanks for the quick response. Extra Utilities just started crashing a bunch for reasons that make no sense as I was trying to solve this problem and I am beginning to think there is just something weird about the mod that just gets messed up whenever I update it. Sorry to bother with a problem that seems like it really doesn't apply to you. Flat colored blocks is a great mod and I really love it so keep up the good work!
