### ISSUE TITLE
wierd characters in block tooltip

### ISSUE THREAD

**Issue by Pitigoi** [ChiselsAndBits/FlatColoredBlocks#34]
right after the hue,will add pictures

**Comment by AlgorithmX2** [comment]
Its supposed to be a ° I guess it doesn't always work though.

**Comment by Pitigoi** [comment]
isnt there a way you could modify this with a language file?

**Comment by AlgorithmX2** [comment]
The current display is determined by the code, I didn't think there would be any issues with displaying that character, I'll need to change to 'deg' and localize it.
