### ISSUE TITLE
full colours

### ISSUE THREAD

**Issue by Pitigoi** [ChiselsAndBits/FlatColoredBlocks#35]
how good of a computer is required for 16777216 colors of one block type?

**Comment by AlgorithmX2** [comment]
I wouldn't know, you would at least need "NotEnoughIds" to extend the block id limit.

FCB isn't that demanding, but that would use a size-able amount of memory just to keep track of the ids and references, I imagine whats in MC to keep track of those blocks would exceed what FCB would use to accomplish said task.
