### ISSUE TITLE
Noticable fixes need porting to 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/FlatColoredBlocks#36]
Same thing I explained to him https://github.com/Brian-Wuest/MC-Prefab/issues/33

**Comment by AlgorithmX2** [comment]
"Please port new structures to 1.10.2" what does this have to do with Flat colored blocks?

**Comment by P3rf3ctXZer0** [comment]
They also added new 1.11.2 features with no 1.10.2 port

**Comment by AlgorithmX2** [comment]
Flat Colored Blocks has had no new features post 1.10.2; And Not everyone will feel like back porting those features anyway.
