### ISSUE TITLE
Can't change config in-game

### ISSUE THREAD

**Issue by Richhobo1216** [ChiselsAndBits/FlatColoredBlocks#39]
The mod description on Curse says that there is a functionality to change the config in-game, but when I click on the 'Config' button on the mod, it just takes me to the 'tutorial' config editor. I don't know if this is a bug or if I'm just doing it wrong, but any help would be greatly appreciated.

**Comment by AlgorithmX2** [comment]
![image](https://cloud.githubusercontent.com/assets/2846930/25412985/8115fc2c-29ec-11e7-88cb-b3932abeeda1.png)
![image](https://cloud.githubusercontent.com/assets/2846930/25413005/86d86258-29ec-11e7-9602-bccf19dbfc26.png)
![image](https://cloud.githubusercontent.com/assets/2846930/25413007/8a65016a-29ec-11e7-9abf-c897e09d1824.png)

I'm not seeing any issues, please refer to the screen shots above, and make sure you have the correct mod selected when you click 'config'

All these settings are also available in the config file stored with the instance of minecraft as well.

**Comment by Richhobo1216** [comment]
Maybe it's the version of Forge that I'm using? I'm using 2282, but I see that you're using 2233. I know that I can change them in the config files, but it would be more convenient to be able to change it in-game. I guess I'll change my Forge version and try it again. Thanks for the help!

**Comment by AlgorithmX2** [comment]
It looks like something changed regarding the config screen in the newer builds of forge, I'll need to look into it.

**Comment by AlgorithmX2** [comment]
I found the change, they are using a new method to create the gui now, so I'll need to release an update that implements the new method as well.

**Comment by Richhobo1216** [comment]
Thanks a lot!
