### ISSUE TITLE
Item to find closest shade

### ISSUE THREAD

**Issue by Richhobo1216** [ChiselsAndBits/FlatColoredBlocks#40]
I would like an item that you can use to find the closest shade to what you want. What I mean by this is that you input an RGB or hexadecimal value, and the item finds the shade that matches your input the most out of the shades available.

**Comment by AlgorithmX2** [comment]
Basically this is a duplicate of https://github.com/AlgorithmX2/FlatColoredBlocks/issues/10

**Comment by Richhobo1216** [comment]
Oh ok you just changed the title of it. I created a new one because #10 was different when I made it.

**Comment by AlgorithmX2** [comment]
Yeah, the description has evolved over time, so It really needed to be updated. It wasn't obvious that this was a duplicate unless you read over the details on that one.
