### ISSUE TITLE
[1.12] ShowBlocksInJEI Not Working

### ISSUE THREAD

**Issue by SnowShock35** [ChiselsAndBits/FlatColoredBlocks#44]
Hi Algo,

Quick bug report for you for Flat Colored Blocks in Minecraft 1.12. Here's the details:

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- Flat Colored Blocks mc1.12-6.1
- Other Mods:
    - Just Enough Items (JEI) 4.7.1.69 

### Issue Description

The `ShowBlocksInJEI` configuration option is no longer being respected in the latest version of the mod. I believe this is because of changes to JEI's API.

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1498838460-7ebbe808.png)
![](https://ss.blamesnow.co.uk/2017/06/1498838765-e5ce55ef.png)

**Comment by AlgorithmX2** [comment]
This was caused by the registration changes, I was registering the block with the API, but the block and the item were not associated yet so it didn't work. 

I changed it so i'm associating the item instead and that fixed it.

**Comment by SnowShock35** [comment]
Close Enough! 😜 Thanks Algo

**Comment by mojoyup1528** [comment]
I will confirm that this is still an issue with 1.12.2 July/12/19 only because I am not sure what the fix is above. What should I do as a user on my end? Thank you Algo and others :)
