### ISSUE TITLE
Texture bug with Ender Compass mod (1.12)

### ISSUE THREAD

**Issue by ImAK9** [ChiselsAndBits/FlatColoredBlocks#45]
https://imgur.com/a/GXv4w & https://imgur.com/a/IlPdk

I have no idea why this happens.

**Comment by ImAK9** [comment]
Ive reported it to the Ender Compass author too.

**Comment by AlgorithmX2** [comment]
I cannot imagine why, The crafter icon / model use the standard asset system, nothing fancy just a JSON  in the proper place that gets loaded like any item.

**Comment by ImAK9** [comment]
So Ender Compass is the problem?

**Comment by AlgorithmX2** [comment]
I can't say for certain, but based on the fact that the model assignment uses the simple JSON method, I'm inclined to say that that seems more likely, but I don't know how they are doing things either.

I honestly don't know anything about that mod.

**Comment by ImAK9** [comment]
Well i disabled it for now, no way im disabling Flat colored blocks....

**Comment by ImAK9** [comment]
It seem to fix it when i disabled it so my guess would be that Ender Compass is the problem here.

**Comment by oitsjustjose** [comment]
I wouldn't be so sure. I'm experiencing the same exact issue with Wearable Backpacks - and it doesn't do it on its own nor with any of the other mods installed (62 other mods). I will gladly provide more info if needed, but I think this is on FCB's end.

When are models being registered? I found that with the new registry system you **have** to do it in pre-init or else everything seems to get mad...

**Comment by AlgorithmX2** [comment]
The Crafter item doesn't register any models, Forge/MC just loads the model on its own as is normal.

The blocks get their models assigned during the register block / item events. It didn't seem to work if I did it before that.

I honestly don't know, I spent 5 hours the other day trying to figure out why C&B's Tank won't render as an item, and I still have no idea.

**Comment by oitsjustjose** [comment]
Odd... well, if it helps any I too had to re-work all of [my model registration](https://github.com/oitsjustjose/Geolosys/blob/master/src/main/java/com/oitsjustjose/geolosys/util/ClientRegistry.java) for the new 1.12 system, maybe that'll help. It's particularly odd not having to register blocks but instead just ItemBlocks, but hey - it works.

**Comment by AlgorithmX2** [comment]
This should be fixed now, calling setCustomModelResourceLocation before the item registration phase results in collisions of delegates.
