### ISSUE TITLE
Crashes when opening creative menu.

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/FlatColoredBlocks#46]
We have confirmed that this mod causes this problem, it goes like this:
Download the newest version of FCB, opening the creative menu then clicking the [>] icon at the top, to change page, the game meets in unfortunate fate and crashes.
I'm bringing this to your attention as soon as I found out, so I'm hoping you can have a fix out for it just as fast.
Regards,
**-L0ST**

**Comment by AlgorithmX2** [comment]
I cannot reproduce this, please provide crash log.

**Comment by ghost** [comment]
I can't find the log. I'll try get it later.

**Comment by brisingraerowing** [comment]
@L0ST5ILVER 
I assume it is similar to [this crash log](https://gist.github.com/BrisingrAerowing/db6ebf5469b5587c0af0ec2b11c539cc).

**Comment by AlgorithmX2** [comment]
@shadowfacts

https://github.com/shadowfacts/UnderwaterUtilities/blob/04396f411990433b3c0f3fb462e2062f70fb9fc9/src/main/kotlin/net/shadowfacts/underwaterutilities/block/tank/ItemBlockTank.kt#L30

Believe you need to add a method here,

for example: https://github.com/AlgorithmX2/Chisels-and-Bits/commit/fb38943bce9c30c09773f2b3b03036b147266960#diff-617810317411c8f3ddf74d4e39088abb

This method seems to have changed in 1.12 for some reason or another.

**Comment by ghost** [comment]
Okay!

**Comment by shadowfacts** [comment]
Indeed I do, I could have sworn I fixed that for all of my mods, but I guess I forgot one. A new version of UnderwaterUtilities will be out shortly.

**Comment by AlgorithmX2** [comment]
I'll mark this as closed, unless @L0ST5ILVER has a second mod with the same problem. But I'll need a log to check on if that is the case.
