### ISSUE TITLE
Stop glowing blocks from "glowing"

### ISSUE THREAD

**Issue by ResqDiver1317** [ChiselsAndBits/FlatColoredBlocks#47]
Is it possible in the config to make the glowing blocks not fluctuate but still emit light? I want to use them on some floors so they light the room, but don't want the fluctuation effect to be there.

**Comment by AlgorithmX2** [comment]
are you talking about the light "shimmering"? or are you talking about the texture? if your talking about the texture, just open the config gui, and change the texture, I believe there is one with no animation.

**Comment by ResqDiver1317** [comment]
I'm referring to the effect where the glowing blocks get brighter/dimmer visually. They appear to have change shades between 3 or 4 shades.

**Comment by AlgorithmX2** [comment]
I can only assume your talking about the texture, rather then the block light effect, since its more subtle.

Open the Mod options and go to FlatColoredBlocks, then Texture, change the glowing texture to one of the other options, flawless for instance.

**Comment by ResqDiver1317** [comment]
lol for some reason my editor didn't show me the whole config when I looked the first time. Just to make sure, I need to change 
DISPLAY_TEXTURE_GLOWING=PULSE   to 
DISPLAY_TEXTURE_GLOWING=DRYWALL
? If I understand right, this will make it look like the regular, only emit light?

**Comment by AlgorithmX2** [comment]
I would recommend using the in game config, over editing the config files manually, however that should work.

**Comment by ResqDiver1317** [comment]
ok, does the in game config edit the actual config file? I only ask because myself and the other staff who are working on setting up the new server for our community are using a github so we can all keep track of the changes so any config changes made, we are documenting/editing the copies of the files we have on the git as well in case anyone is doing local testing on their own private server so we can keep everything the same.

**Comment by AlgorithmX2** [comment]
Yes, the in game config editor saves new copies of the files.

**Comment by ResqDiver1317** [comment]
Nice! last question, and I feel like I should know this, how do I use the in game editor? I found /edit_config but it only shows ftbu, ftbl, and yabba?

**Comment by ResqDiver1317** [comment]
nvm, found it :) Thanks for your help. much better now!
