### ISSUE TITLE
1.12.1 - Crash with Chisel Present

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/FlatColoredBlocks#49]
https://github.com/Chisel-Team/Chisel/issues/519

**Comment by AlgorithmX2** [comment]
Does the crash reproduce without optifine?

**Comment by P3rf3ctXZer0** [comment]
I will test it tomorrow.

**Comment by AlgorithmX2** [comment]
I've confirmed optifine is not in play, and I've replied to the original chisel issue.

**Comment by P3rf3ctXZer0** [comment]
This has been fixed for a while my bad.
