### ISSUE TITLE
Interaction concerns with Architecturecraft - Keep this open till its resolved.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/FlatColoredBlocks#52]
https://github.com/elytra/ArchitectureCraft/issues/9

**Comment by darkevilmac** [comment]
So how does flatcolouredblocks store colour data? Is there an unlisted prop with a tile or is it just registering a bunch of blocks with different states? I wasn't able to gather that based on my fairly quick look.

**Comment by AlgorithmX2** [comment]
Its stored as a true state, https://github.com/AlgorithmX2/FlatColoredBlocks/blob/1.12/src/main/java/mod/flatcoloredblocks/block/BlockFlatColored.java#L156

And colors for blocks and items are available via standard IItemColor / IBlockColor
https://github.com/AlgorithmX2/FlatColoredBlocks/blob/1.12/src/main/java/mod/flatcoloredblocks/client/ClientSide.java#L54

**Comment by darkevilmac** [comment]
Looks like IBlockColor wasn't implemented in ArchitectureCraft by the original dev (or it was removed during my refactor), it should be fine to close this issue as I believe I've solved the problem on my repo.
