### ISSUE TITLE
Forge freezes upon startup after installing FCB

### ISSUE THREAD

**Issue by romeodisk** [ChiselsAndBits/FlatColoredBlocks#53]
MC version: 1.12.2
Forge version: 1.12.2-14.23.0.2512

I installed FCB. I tried to open Minecraft. It was loading fine until it suddenly froze and the window said "Not Responding". I only encountered this after installing FCB. Is there some kind of issue that's causing Forge to freeze? (Screenshot attached)

![image](https://user-images.githubusercontent.com/29274674/31719031-af1cc7a8-b444-11e7-8fd3-6cda2142405e.png)

**Comment by AlgorithmX2** [comment]
I cannot reproduce this, Maybe check your log?
