### ISSUE TITLE
No yellow blocks?

### ISSUE THREAD

**Issue by xAlicatt** [ChiselsAndBits/FlatColoredBlocks#56]
When I have nothing but yellow minecraft dye and cobble in my inventory, I'm not getting anything showing up in the block maker? It seems to work fine with most other dyes (I haven't tried them all) but for some reason having ONLY yellow leaves me with no blocks available. Is this normal? Am I missing something? I thought maybe it was because yellow is a primary color, but blue and red both work as expected.

**Comment by AlgorithmX2** [comment]
Are you using the default configuration?
![image](https://user-images.githubusercontent.com/2846930/39951747-8c538cfc-5552-11e8-9bb8-144376cdd1fb.png)
Is what I'm seeing.

**Comment by xAlicatt** [comment]
Yes as far as I know. :/ It so weird that it seems to be only yellow that's doing this. It's probably some random mod conflict.

**Comment by xAlicatt** [comment]
OK so I went and looked at my config file, and yes I did change it. I changed the following lines so we would use less IDs from the default of 32:

    I:HUE_SHADES=16
    I:HUE_SHADES_GLOWING=16
    I:HUE_SHADES_TRANSPARENT=16

But I didn't touch anything else. I tested it with the default config and it works as expected, but changing only these lines makes it so that no yellow blocks exist. This seems (to me) to be an error/issue, since like I was saying, it doesn't seem to happen with any of the other dyes.

**Comment by AlgorithmX2** [comment]
Yellow itself is a pretty slim window on the color wheel, orange is basically right on top of it too, which means that this adjustment that changes it from 10 degrees to 20 degrees per hue more or less removes pure yellows from the blocks.

With those configs the most yellow blocks are really more of a "gold" and thus are tied to orange dyes instead of yellow.
