### ISSUE TITLE
Block ID forcing override on place block

### ISSUE THREAD

**Issue by SwordKorn20** [ChiselsAndBits/FlatColoredBlocks#6]
I am currently experimenting with new mods for 1.8.9 and I have this mod alongside OpenComputers. The issue I have found is when a Tier 3 screen from OpenComputers is in the world, it is forcibly turned into a Dark Lime Block #353.

This happens to any screens already placed and upon placement of any new screens. I'm not sure if this is Sangar or yourself but I thought I'd mention it here.

**Comment by AlgorithmX2** [comment]
I'm in inclined to say its OpenComputers.. or maybe something else.. maybe a forge bug.. FCB is pretty much "blocks" there is basically no logic or anything to them, they are pretty simple I can't imagine them doing something like that.

**Comment by SwordKorn20** [comment]
It seems to just affect the screens. The bug seems to only affect the screens though. It's unusual and makes me glad I've always been inclined to creative test miss first as Sangar has fairly expensive recipes for his screens at the higher tiers. I'm not here to vent or say it's specifically your mod or the other. I just wanted to bring it to light.

**Comment by AlgorithmX2** [comment]
Sure, Make sure your on the latest forge, and see what the OC folks say, like I said, it might be some kinda forge related issue even.

I really don't know, I just can't imagine my blocks, which are basically glorified cobblestone causing an issue, OC is probably in comparison infinite more complicated, and Forge is responsible for managing all the registries... so either of those makes much more sense.

**Comment by SwordKorn20** [comment]
Hi AlgorithmX2! I went to Sangar with the issue and he was confused as well until he noticed a mistake in his code:

"Looks like I screwed up meta in rotatables in the 1.8 -> 1.8.8 port, whoops."

Glad to report this is nothing to do with your mod and his next update should fix the problem :)

**Comment by AlgorithmX2** [comment]
Thanks for reporting back, glad its all figured out now.

**Comment by SwordKorn20** [comment]
My pleasure! I didn't want you worrying about a potential bug in your mod when it was simple coder error in another!
