### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Dream-of-the-Phoenix** [ChiselsAndBits/FlatColoredBlocks#61]
1.
Could you please make the default color blocks as a texturepack? Just replace the vanilla blocks. I would need the texture for the "Spritecraft" program. This program takes images and converts them to Minecraft blocks. But I would like to use the (default) colors of your mod for the images.

2.
I don't know how much work it takes, but you could maybe make a own program that converts images to minecraft pixel. (chisel and bits pixel maybe) I would like to see a program where I can load images and convert them into minecraft chisel and bits images. It would then also cool if you could just copy your mods into a mod folder of the program and then it would also load the textures of the mods.

**Comment by AlgorithmX2** [comment]
1. I don't see any reason to make a texture pack that changes all of vanilla blocks into random colors from this mod... that is what the mod is for it adds the blocks and the colors. It also only uses 1 texture for most of the blocks making thousands of blocks. 

2. I honestly have no idea what your trying to explain, something about converting images and chisels and bits. I just don't know what your asking for.

If anything this suggestion sounds like you don't want to use my mod, but just want me to make other things so you can avoid using it... which doesn't really make any sense to me.

**Comment by Dream-of-the-Phoenix** [comment]
Sorry, I should have made it clear for what I would need a texturpack.

 I like to build Pixel art with chisel and bits. Last week I found your second mod.
 When I make Pixelart i use the "SpiritcraftFull" Programm.
 And there you can say what blocks from Minecraft this Programm should use. There I would use a  
 texturpack of this mod, so that I get a Pixelart with the blocks of your mod in it. And then I would build
 the Pixel art with chisel and bits and your mod in Minecraft.

![2019-03-09 (2)](https://user-images.githubusercontent.com/48368273/54069419-2366b680-4258-11e9-93d5-f7ce1aab9ee6.png)

I really love your mods. I can build anything I could think of.
And you really couldn't play Minecraft with a texturpack of flat Color blocks. Because the whole world would then be colored "really interresting".

But it is ok for me if you don't want, I just wanted now that you understand what I meant.
Do you Maybe know a Programm where you can say with which RGB Colors the Image should be converted to a pixelart?
That would also work. All block of this mod have a RGB Code.

Thanks for the quick Reply.

Dream of the Phoenix
![2018-12-12_22 50 02](https://user-images.githubusercontent.com/48368273/54069739-80636c00-425a-11e9-9a97-1da237457fcb.png)
