### ISSUE TITLE
Hue shades values that are divisors of 360 (eg. 72) will crash the game during loading.

### ISSUE THREAD

**Issue by pressRtowin** [ChiselsAndBits/FlatColoredBlocks#63]
It erroneously claims that your max value isn't greater than your min.

**Comment by AlgorithmX2** [comment]
With everything else as the default I adjusted HUE_SHADES to 72 for each normal, glowing and transparent. The game started fine.

**Comment by AlgorithmX2** [comment]
I changed the range to 0.0 -> 1.0 for hues, and still no crash. It might be easier to reproduce if you just pastebin the config that produces a crash.

**Comment by pressRtowin** [comment]
Maybe try setting the exponent to 1?
I believe this is the exact settings I was using when it was crashing:
[flatcoloredblocks.cfg.txt](https://github.com/AlgorithmX2/FlatColoredBlocks/files/3219750/flatcoloredblocks.cfg.txt)

**Comment by AlgorithmX2** [comment]
Should be fixed in v6.8
