### ISSUE TITLE
You said to post ideas/suggestions here. 

### ISSUE THREAD

**Issue by Nosinpi** [ChiselsAndBits/FlatColoredBlocks#9]
Perhaps you yourself or if it were possible for somebody else to add 3D printing to the mod as an addon. Instead of just making copies with paper and then right clicking it, you could have a scanner and printer. Place the creation you made in the scanner and it gives you the stencil. Then put the stencil in the printer and it prints it. Perhaps even develop some web application where people could create something outside of the game and it generates a specific code which is tied into the mod, and then you go to the printer and paste that code and it will grab the schematic and tell you what chisels and bits you need to print it. It could even possibly store your stencils and rename them, store all your bits, etc.

**Comment by Nosinpi** [comment]
This is the wrong mod. My apologies.

**Comment by AlgorithmX2** [comment]
Your right, this is the wrong mod...

With Chisels & Bits, That is all possible as an add-on ( the api allows for such things ), I plan on adding sharing capabilities native to C&B, which will let you export and import patterns and such from one game into another game, and share them online, I don't have any plans on running a site to facility it however, I will be aiming for something a bit more De-centerallized.

**Comment by Nosinpi** [comment]
Sounds good. I watch Direwolf's Forgecraft series and really look forward to the future of C&B. I would like to contribute to an add-on as I mentioned but I have no clue how Forge works. Have only made a private Spigot plugin which was sort of a EE3/ProjectE spinoff for infinite storage for a friend's server that never got off. Spigot plugin developing is pretty dull. Planning on getting into Forge this Summer though. I've been writing an idea for an AE2 addon that implements wireless networks. Involves sending satellites into space with IP addresses that you connect your network too, firewalls for multiplayer servers (and hacking tools), wireless transfer nodes for items, energy, redstone signals, etc., an atomic suit and handheld device that lets you set coordinates to teleport to, etc. But that's probably shooting for the moon right now. Think my first mod will be remaking the way enchanting is done since nobody has really touched that aspect of the game. Was thinking of practicing multiblock structures by making different level "spiritual shrines" for each level of enchantments and you place your item in it and every night at midnight, it enchants that items. There would be some sort of crucible that you would need to convert your XP to liquid and keep filled, or else bad things may happen. May add a few custom enchantments as well.

**Comment by AlgorithmX2** [comment]
Gonna go ahead and close this issue, since its on the wrong mod.. and since I already have the sharing features planned.
